// Generated by CoffeeScript 1.3.3
(function() {

  $.ready = function() {
    var animateFist, dispScores, fist, fistStep, getHighScores, health, healthBar, healthInterval, punch, punching, reverse, score, sendMsg, sendScore, slowInterval, splodeid, updateHealth, wSplosion, wolfsplosion;
    $('img').bind('dragstart', function(event) {
      return event.preventDefault();
    });
    health = 0;
    score = 0;
    splodeid = 0;
    fistStep = -1;
    wSplosion = false;
    reverse = false;
    punching = false;
    healthBar = $('div#health');
    sendMsg = function(msg) {
      return $('span#message').html(msg);
    };
    sendScore = function(name, cb) {
      var req;
      return req = jQuery.ajax('http://wolfpuncher.com:6578/score', {
        type: 'POST',
        dataType: 'json',
        data: {
          name: name,
          score: Math.round(score)
        },
        success: function(data) {
          return cb(data);
        }
      });
    };
    getHighScores = function(cb) {
      var req;
      return req = jQuery.ajax('http://wolfpuncher.com:6578/scores', {
        type: 'GET',
        dataType: 'json',
        success: function(data) {
          return cb(data);
        }
      });
    };
    updateHealth = function(diff) {
      if (!wSplosion) {
        if (health + diff >= 0 && health + diff <= 100) {
          health += diff;
          healthBar.width(7.6 * health);
          if (health > 80) {
            healthBar.css('background-color', '#0C0');
            if (reverse) {
              score += .1;
            }
            if (!reverse) {
              sendMsg('PUNCH THE WOLF!!');
              reverse = true;
            }
          }
          if (health < 80 && health > 40) {
            healthBar.css('background-color', '#CC0');
            if (!reverse) {
              sendMsg("GET READY...");
            }
            if (reverse) {
              score += .2;
            }
          }
          if (health < 40 && health > 10) {
            healthBar.css('background-color', '#D50');
            if (!reverse) {
              sendMsg("WAIT...");
            }
            if (reverse) {
              score += .5;
            }
          }
          if (health < 10) {
            healthBar.css('background-color', '#C00');
            if (reverse) {
              score += 1;
              sendMsg('');
            }
          }
        } else if (health + diff < 0) {
          wolfsplosion();
        }
      }
      return $('span#score').html("SCORE: " + (Math.round(score)));
    };
    wolfsplosion = function() {
      var flashBar, splosionsInterval;
      if (!wSplosion) {
        wSplosion = true;
        sendMsg("WOLF SPLOSION!!");
        $('img#wolf').attr('src', 'imgs/red_wolf.png');
        $('audio#wolfsplosion').trigger('play');
        flashBar = setInterval(function() {
          if (healthBar.css('background-color') !== 'rgb(255, 0, 0)') {
            return healthBar.css('background-color', '#F00');
          } else {
            return healthBar.css('background-color', '#FFF');
          }
        }, 30);
        splosionsInterval = setInterval(function() {
          $('div#container').append("<img src='imgs/splosion.gif' id='splode-" + splodeid + "' class='splosion' />");
          $('#splode-' + splodeid).css({
            'bottom': splodeid * 40 * Math.random() * 5,
            left: splodeid * 40 * Math.random() * 5
          });
          return splodeid++;
        }, 500);
        return $('img#wolf').animate({
          bottom: '-600px'
        }, 6000, function() {
          $('audio#toobad').trigger('play');
          $('img#fist').hide();
          $('img#title').hide();
          $('img#wolf').hide();
          $('.splosion').hide();
          $('.end').show();
          healthBar.hide();
          clearInterval(flashBar);
          clearInterval(splosionsInterval);
          sendMsg("");
          $('div#container').css({
            backgroundColor: '#000',
            backgroundImage: 'url(\'imgs/wolfgrave.jpg\')'
          });
          return setTimeout(function() {
            return $('div#container').css({
              backgroundColor: '#000',
              backgroundImage: 'url(\'imgs/toobad.jpg\')'
            });
          }, 1800);
        });
      }
    };
    healthInterval = setInterval(function() {
      return updateHealth(1);
    }, 50);
    slowInterval = setInterval(function() {
      return animateFist();
    }, 250);
    fist = $('img#fist');
    animateFist = function() {
      if (!punching) {
        fistStep++;
        if (fistStep === 0) {
          fist.css({
            top: '20px',
            right: '40px'
          });
        }
        if (fistStep === 1) {
          fist.css({
            top: '30px',
            right: '30px'
          });
        }
        if (fistStep === 2) {
          fist.css({
            top: '20px',
            right: '20px'
          });
        }
        if (fistStep === 3) {
          fist.css({
            top: '30px',
            right: '30px'
          });
          return fistStep = -1;
        }
      }
    };
    punch = function() {
      if (!wSplosion) {
        punching = true;
        if (Math.random() * 20 < 2) {
          $('audio#whine1').trigger('play');
        }
        if (Math.random() * 20 > 18) {
          $('audio#whine2').trigger('play');
        }
        $('div#container').css('background-image', 'none');
        $('img#wolf').css({
          width: '360px',
          height: '420px'
        });
        fist.css({
          width: '300px',
          height: '340px'
        });
        fist.css({
          top: '80px',
          right: '200px'
        });
        setTimeout(function() {
          return $('div#container').css('background-image', "url('imgs/forest.jpg')");
        }, 50);
        setTimeout(function() {
          $('img#wolf').css({
            width: '',
            height: ''
          });
          fist.css({
            width: '',
            height: ''
          });
          fist.css({
            top: '30px',
            right: '30px'
          });
          return punching = false;
        }, 150);
        health -= 5;
        return $('audio#hit').trigger('play');
      }
    };
    $('img#wolf').on('mousedown', function() {
      return punch();
    });
    $(window).keydown(function(e) {
      if (e.which === 32) {
        e.preventDefault();
        return punch();
      }
    });
    $('span#see-scores').click(function() {
      return getHighScores(function(data) {
        return dispScores(data);
      });
    });
    $('span#see-scores').mouseover(function() {
      return $(this).css('cursor', 'pointer');
    });
    $('input#name').focus(function() {
      return $(this).val('');
    });
    $('button#submit').click(function() {
      var name;
      name = $('input#name').val();
      return sendScore(name, function(data) {
        $('input#name').hide();
        $('button#submit').hide();
        $('audio#getalife').trigger('play');
        return dispScores(data);
      });
    });
    dispScores = function(scores) {
      var element, entry, index, list, _i, _len;
      list = '';
      for (index = _i = 0, _len = scores.length; _i < _len; index = ++_i) {
        element = scores[index];
        entry = element.split(':');
        list += entry[0] + '..........' + entry[1] + '\n';
      }
      return alert(list);
    };
    return $('img#muter').click(function() {
      var music;
      music = $('audio#music');
      if (music[0].paused) {
        $(this).attr('src', 'imgs/mute-off.png');
        return music.trigger('play');
      } else {
        $(this).attr('src', 'imgs/mute-on.png');
        return music.trigger('pause');
      }
    });
  };

}).call(this);
