// Generated by CoffeeScript 1.3.3
(function() {
  var app, checkScore, db, express, redis;

  express = require('express');

  redis = require('redis');

  db = redis.createClient();

  app = express();

  app.use(express.bodyParser());

  checkScore = function(score) {
    score = parseInt(score);
    if (score === NaN) {
      return false;
    } else {
      return score;
    }
  };

  app.post('/score', function(req, res) {
    var name, score;
    name = req.body.name.toUpperCase();
    if (name.length > 3) {
      console.log('name len');
      return res.send({
        msg: 'It fucked up. Stop fucking around.'
      });
    } else {
      score = parseInt(req.body.score);
      if (score === NaN) {
        console.log('nan');
        return res.send({
          msg: 'It really fucked up. What are you doing'
        });
      } else {
        db.zadd('wpscores', score, name + ':' + score);
        res.type('json');
        return res.send({
          msg: 'Wow. Great Job.'
        });
      }
    }
  });

  app.get('/scores', function(req, res) {
    return db.zrevrange('wpscores', 0, 9, function(err, data) {
      if (err) {
        throw err;
      }
      res.type('json');
      return res.send(data);
    });
  });

  app.listen(6578);

}).call(this);
